<?php require VIEWS_PATH . 'includes/header.phtml';?>

  <div class="container"> 
    
    <div class="jumbotron">
      <h1>Sobre</h1>
    </div>
    
    <div class="col-md-12">
   
    <h2>A Instituição</h2>
    <p>
        Mais informações entre em contato para conosco para tirar todas as suas dúvidas; Mais informações entre em contato para conosco para tirar todas as suas dúvidas. Mais informações entre em contato para conosco para tirar todas as suas dúvidas.   
      </p>

      <h2>Nossas Metas</h2>
      <p>
      Mais informações entre em contato para conosco para tirar todas as suas dúvidas; Mais informações entre em contato para conosco para tirar todas as suas dúvidas. Mais informações entre em contato para conosco para tirar todas as suas dúvidas.    
      <h2>Desafios</h2>
      <p>
        Mais informações entre em contato para conosco para tirar todas as suas dúvidas; Mais informações entre em contato para conosco para tirar todas as suas dúvidas. Mais informações entre em contato para conosco para tirar todas as suas dúvidas.   
      </p>
    
      <h2>Práticas</h2>
      <p>
        Mais informações entre em contato para conosco para tirar todas as suas dúvidas; Mais informações entre em contato para conosco para tirar todas as suas dúvidas. Mais informações entre em contato para conosco para tirar todas as suas dúvidas.   
      </p>

    <h2>Valores</h2>
    <p>
        Mais informações entre em contato para conosco para tirar todas as suas dúvidas; Mais informações entre em contato para conosco para tirar todas as suas dúvidas. Mais informações entre em contato para conosco para tirar todas as suas dúvidas.   
      </p>

    </div>

  </div>  
  
  
<?php require VIEWS_PATH . 'includes/footer.phtml';?>