
<!-- chama o header primeiro -->
<?php require VIEWS_PATH . 'includes/header.phtml';?>

<div class="container">

    <!-- Main component for a primary marketing message or call to action -->
    <div class="jumbotron">
      <h1>Entre em Contato Conosco</h1>
    </div>

    <div class="col-md-12">
      <h2>Fale Conosco por meio dos contatos abaixo!</h2>
      <p>
        Telefone: <a href="tel:999999999999"><strong>(21) 97303-2281</strong></a></br>
        Email: <a href="antonio.rufino1802@gmail.com"><strong>email@gmail.com</strong></a>
      </p>

      <p>
            <form>
            
                <div class="form-group">
                  <label for="exampleInputEmail1" >Nome (campo obrigatório)</label>
                  <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder= "Insira o nome completo" name="name">
                  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>

                <div class="form-group">
                  <label for="exampleInputPassword1">Email (email obrigatório)</label>
                  <input type="email" class="form-control" id="exampleInputPassword1" placeholder= "Insira seu melhor email" name="email">
                </div>

                <div class="form-group">
                    <label for="exampleInputEmail1" >Menssagem</label>  
                    <textarea name="message" id="" cols="30" rows="10" class="form-control"></textarea>  
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
      </form>
      </p>
    </div>


</div> <!-- /container -->

<!-- chama o footer -->
<?php require VIEWS_PATH . 'includes/footer.phtml';?>